homeassistant:
  ingress:
    host: ha.parkl.ee
    servicePort: 443
zigbee2mqtt:
  ingress:
    host: z2m.parkl.ee
    servicePort: 443
mosquitto:
  websocketPort: 9001
  tlsPort: 8883
akri:
  kubernetesDistro: k8s
  udev:
    discovery:
      enabled: true
openebs:
  engines:
    replicated:
      mayastor:
        enabled: false
  zfs-localpv:
    zfsNode:
      kubeletDir: /var/lib/kubelet
