mosquitto:
  ingress:
    subDomain: mqtt
    websocketPort: 9001
    websocketNodePort: 30001
    mqttsPort: 8883
    mqttPort: 1883
  account:
    username: admin
    password: changeme
  volume:
    data:
      size: 8Gi

zfs:
  poolName: zfspv-pool
