apiVersion: v2
name: zigbee2mqtt
description: A Helm chart for Zigbee2MQTT
version: 0.1.0
type: application
dependencies:
  - name: cert-manager
    version: ">=1.19.1"
    repository: https://charts.jetstack.io

  - name: akri
    version: ">=0.13.8"
    repository: https://project-akri.github.io/akri
